Repository s7917/Hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#1 Create Binary.cpp
  Binary.cpp
Labels: hacktoberfest

#2 Create odd_even.cpp
  odd_even.cpp
Labels: #hacktoberfest Accepted

#3 Update Binary.cpp
  Binary.cpp
Labels: hacktoberfest

#4 arr.c
  arr.c
Labels: hacktoberfest

#10 Create exponential.cpp
  exponential.cpp
Labels: hacktoberfest

#8 Create insertion.cpp
  insertion.cpp
Labels: hacktoberfest

#7 Create bubblesort.cpp
  bubblesort.cpp
Labels: hacktoberfest

#11 Create reversearray.cpp
  reversearray.cpp
Labels: hacktoberfest

#6 Create quicksort.cpp
  quicksort.cpp
Labels: hacktoberfest

#12 Merge 2 sorted arrays(Cpp)
  Merge-2-Sorted-Arrays.cpp
Labels: hacktoberfest

#13 Create Linearsearch.cpp
  Linearsearch.cpp
Labels: hacktoberfest

#14 Create Treesort.cpp
  Treesort.cpp
Labels: hacktoberfest

#15 Create Topological_Sorting.cpp
  Topological_Sorting.cpp
Labels: hacktoberfest

#5 Added prime & fibonacci check
  fibonacci_no.cpp
  prime_no.cpp
Labels: hacktoberfest

#17 Create Average In The Array
  AverageInTheArray.cpp
Labels: hacktoberfest

#16 Create reversenumber.cpp
  reversenumber.cpp
Labels: hacktoberfest

#19 Create Max_in_subarray.cpp
  Max_in_subarray.cpp
  peakelementarray.cpp
Labels: hacktoberfest Accepted

#20 Updated the Directory Structure.
  Array/AverageInTheArray.cpp
  Array/Max_in_subarray.cpp
  Array/Merge-2-Sorted-Arrays.cpp
  Array/arr.c
  Array/peakelementarray.cpp
  Array/reversearray.cpp
  Searching/Binary.cpp
  Searching/Linearsearch.cpp
  Sorting/Topological_Sorting.cpp
  Sorting/Treesort.cpp
  Sorting/bubblesort.cpp
  Sorting/exponential.cpp
  Sorting/insertion.cpp
  Sorting/quicksort.cpp
Labels: good first issue, hacktoberfest, hacktoberfest Accepted

#21 Create-Factorial-of-number.cpp
  Create-Factorial-of-number.cpp
Labels: hacktoberfest Accepted

#22 Create kadane_algorithm.cpp
  kadane_algorithm.cpp
Labels: hacktoberfest Accepted

#23 Create-second-largest-element-in-Array.cpp
  .cpp
Labels: hacktoberfest Accepted

#25 added two_sum.cpp
  Array/two_sum.cpp
Labels: hacktoberfest Accepted

#27 added Shell Sort hacktoberfest 2023 contribution
  Sorting/shellSort.cpp
Labels: hacktoberfest Accepted

#26 add MergeSort.cpp
  Sorting/MergeSort.cpp
Labels: hacktoberfest

#30 Create Largest_Special_sum.cpp
  Largest_Special_sum.cpp
Labels: hacktoberfest Accepted

#31 [ADD] sieveOfEratosthenes.cpp
  sieveOfEratosthenes.cpp
Labels: hacktoberfest Accepted

#33 Create 37Sudoku Solver.cpp
  Leetcode/37Sudoku Solver.cpp
Labels: hacktoberfest Accepted

#32 Create 42TrappingRainWater.cpp
  42TrappingRainWater.cpp
Labels: hacktoberfest Accepted

#37 Create Kruskalsalgorithm.cpp
  Kruskalsalgorithm.cpp
Labels: hacktoberfest Accepted

#39 Create 273Integer to English Words.cpp
  Leetcode/273Integer to English Words.cpp
Labels: hacktoberfest Accepted

#40 Create 297. Serialize and Deserialize Binary Tree.cpp
  Leetcode/297. Serialize and Deserialize Binary Tree.cpp
Labels: hacktoberfest Accepted

#41 Create Selection_sort.cpp
  Sorting/Selection_sort.cpp
Labels: hacktoberfest Accepted

#43 Create Traveling Salesman Problem.cpp
  Traveling Salesman Problem.cpp
Labels: hacktoberfest Accepted

#42 Create Dijkstra's Algorithm .cpp
  Dijkstra's Algorithm .cpp
Labels: hacktoberfest Accepted

#46 Added 264.Ugly Number II.cpp in Leetcode
  264. Ugly Number II.cpp
  Leetcode/274. H-Index.cpp
Labels: hacktoberfest Accepted

#45 HacktoberFest 4. Median of Two Sorted Arrays
  Leetcode/4. Median of Two Sorted Arrays.cpp
Labels: hacktoberfest Accepted

#44 Added solution to Longest Substring Without Repeating Characters
  Leetcode/3.LongestSubstringWithoutRepeatingCharacters.cpp
  Leetcode/5.LongestPalindromicSubstring.cpp
Labels: hacktoberfest Accepted

#48 Add Leetcode 1922. Count Good Numbers cpp solution
  Leetcode/1922. Count Good Numbers.cpp
Labels: hacktoberfest Accepted

#47 Added 289. Game of Life.cpp in Leetcode
  Leetcode/289. Game of Life.cpp
Labels: hacktoberfest Accepted

#49 Create binarytree.cpp
  binarytree.cpp
Labels: hacktoberfest Accepted

#50 Add files via upload
  pascal_triangle2.cpp
Labels: hacktoberfest

#51 Add files via upload
  rotaion_2d_array.cpp
Labels: hacktoberfest Accepted

#53 Create Bucketsort.cpp
  Bucketsort.cpp
Labels: hacktoberfest Accepted

#52 Create cyclicSort.cpp
  cyclicSort.cpp
Labels: hacktoberfest Accepted

#54 Create 347-Top K frequent Elements
  347-Top K frequent Elements
Labels: hacktoberfest Accepted

#55 Create 785-Is Graph Bipartite
  Leetcode/785-Is Graph Bipartite
Labels: hacktoberfest Accepted

#56 add swap.cpp
  swap.cpp
Labels: hacktoberfest Accepted

#60 Create minheighttree.cpp
  minheighttree.cpp
  rottenOranges.cpp
Labels: hacktoberfest

#59 Added 3 Sum
  Leetcode/15. 3Sum.cpp
Labels: hacktoberfest Accepted

#61 Update rottenOranges.cpp
  rottenOranges.cpp
Labels: hacktoberfest Accepted

#63 Create floodfillalgo.cpp
  floodfillalgo.cpp
Labels: hacktoberfest Accepted

#62 Added HeapSort
  Sorting/Heapsort.cpp
Labels: hacktoberfest Accepted

#65 Matrix Chain Multiplication.cpp
  Matrix Chain Multiplication.cpp
Labels: hacktoberfest Accepted

#69 Added Leetcode Problem 367 - Valid Perfect Square
  Leetcode/367. Valid Perfect Square.cpp
Labels: hacktoberfest Accepted

#68 add Max_subarray_sum.cpp
  Leetcode/Max_subarray_sum.cpp
  linked_list.cpp
Labels: hacktoberfest Accepted

#67 add armstrong.cpp
  armstrong.cpp
Labels: hacktoberfest Accepted

#70 Update linked_list.cpp
  linked_list.cpp
Labels: hacktoberfest Accepted

#74 Create BeadSort.cpp
  Sorting/BeadSort.cpp
Labels: hacktoberfest Accepted

#77 Update and rename linked_list.cpp to Priyanshu linked_list.cpp
  Linked List/Priyanshu linked_list.cpp
  Linked List/linked_list.cpp
Labels: hacktoberfest Accepted

#83 Ford-Fulkerson Algorithm.cpp
  Ford-Fulkerson Algorithm.cpp
Labels: hacktoberfest Accepted

#87 LinkedList Problem LRU Cache
  Linked List/LRU_Cache.cpp
Labels: hacktoberfest Accepted

#89 Sort elements by frequency.cpp
  Sort elements by frequency.cpp
Labels: hacktoberfest Accepted
